"""WAVE -- a 4-voice wavetable synth as an FX2 effect on the DSP: a port of
CHOMPI WAVE's voice (CHOMPI-Club/CHOMPI a73d732, MIT; LICENSE-CHOMPI) played
by the track's own pitch and envelope through a sine carrier.

`wave.asm` is generated by generate.py. It owns a 16,384-word FX2 buffer
(eight 2,048-sample frames) and DARK REV's harvested words.
"""

from remix.schema import (BusRole, Category, Claims, DspSection, Formatter, Gate, Harness, Kind,
                          MenuEntry, Module, Param, Proof, YBase)
import importlib.util
import pathlib

_spec = importlib.util.spec_from_file_location("wave_generate",
                                               pathlib.Path(__file__).with_name("generate.py"))
_gen = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_gen)

MODULE = Module(
    name="wave",
    key="WAVE",
    kind=Kind.DSP_EFFECT,
    category=Category.TRACK, author="sambanks", author_url="https://github.com/sambanks",
    proof=Proof.HARDWARE, proof_note="Sam's MKII, image 93, 3 Oct 2026: plays, PTCH and the CHROMATIC keys move the pitch",
    doc="Experiment: a 4-voice wavetable synth on FX2; a sine on the track sets its pitch and level.",
    menu=MenuEntry(fx2_id=0x0b, donor_desc=0x400d58b8,     # DARK REV's descriptor
                   abbr=b"WAVE", fullname=b"Wave Synth", build_tag=False),
    params=(
        Param(b"FRAM", 0, active=True, formatter=Formatter.PLAIN,
              doc="wavetable position: sine, tri, saw, square, pulses; morphs between"),
        Param(b"CUT", 80, active=True, formatter=Formatter.PLAIN,
              doc="DJ filter: low-pass below the middle, high-pass above"),
        Param(b"RES", 40, active=True, formatter=Formatter.PLAIN,
              doc="filter resonance"),
        Param(b"CHRD", 0, count=8, active=True, formatter=Formatter.WIDE_STEPPED,
              labels=_gen.CHORD_NAMES,
              doc="the four voices' intervals over the played note"),
        Param(b"OCT", 2, count=5, active=True, formatter=Formatter.STEPPED,
              labels=("-4", "-3", "-2", "-1", "0"),
              doc="octaves below the carrier"),
        Param(b"LEVL", 64, active=True, formatter=Formatter.PLAIN,
              doc="output level"),
        Param(b"FDEP", 0, active=True, formatter=Formatter.PLAIN,
              doc="filter LFO depth"),
        Param(b"FRAT", 9, count=16, active=True, formatter=Formatter.WIDE_STEPPED,
              labels=_gen.RATE_LABELS, doc="filter LFO rate, Hz"),
        Param(b"VDEP", 0, active=True, formatter=Formatter.PLAIN,
              doc="vibrato depth, up to +-2 semitones"),
        Param(b"VRAT", 9, count=16, active=True, formatter=Formatter.WIDE_STEPPED,
              labels=_gen.RATE_LABELS, doc="vibrato rate, Hz"),
        Param(b"DETN", 0, active=True, formatter=Formatter.PLAIN,
              doc="spreads the four voices, up to +-60 cents on the outer two"),
        Param(b"", None, active=False),
    ),
    dsp=DspSection(asm="modules/wave/wave.asm", priority=15,
                   bus_role=BusRole.NONE, ybase=YBase.NEVER,
                   r7_latch_slot=None, gate_label=None,
                   max_per_core=2),
    claims=Claims(stock_instance_buffer=True, buffer_words=16384),
    harness=Harness(layout_char=None, is_server=False),
    gates=(Gate('tools/verify/verify_wave.py', stage='image'),),
)
