; CYCLES_FORWARD_BRANCHES
; WAVE -- a 4-voice wavetable synth as an FX2 effect: a port of CHOMPI
; WAVE's voice (CHOMPI-Club/CHOMPI a73d732, MIT; LICENSE-CHOMPI) onto the DSP.
; Generated by generate.py; edit that.
;
; The track plays a sine (the carrier). Its period, from the interpolated
; rising zero crossing, sets the voices' root (OCT octaves down); its level,
; through two 2 ms one-poles, is the envelope. So PTCH, the CHROMATIC keys,
; SCALE QUANTIZER, p-locks and AMP play the synth.
;
; The FX2 buffer (Y, 16,384 words) holds eight 2,048-sample frames, written
; 256 samples a call after init (sine, triangle, saw, square, pulses 1/4 ..
; 1/32, zero-mean, peak 0.45); the output is silent until they are done.
;
; r7 block: $00 base, $01 generated, $02/$03 sine state, $04 filter LFO
; phase, $05/$06 lp/hp, $07/$08 1/(1-f)/32, $09 frame position, $0a/$0b
; envelope, $0c previous sample, $0d samples since the crossing, $0e its
; fraction, $0f carrier increment, $10 vibrato phase, $11..$24 voices
; (phase, b0, b1, h0, h1), $25..$28 increments, $29..$30 knobs, $31..$3a
; per-sample values, $40..$57 chord ratios / 4, $58..$67 LFO increments.

init:
        move    #>$ffffff,m4
        move    r7,r4
        clr     a
        do      #$68,>wv10
        move    a,x:(r4)+
wv10:
        nop
        move    x:>$213,r4                  ; the allocator's FX2 buffer base
        move    x:(r4),a
        move    a,x:(r7+$00)
        move    #>$39999a,a
        move    a,x:(r7+$03)
        move    #>$040000,a                 ; 1/(1-0), /32
        move    a,x:(r7+$07)
        move    a,x:(r7+$08)
        move    #>$001000,a                 ; 4096: the first crossing only stamps
        move    a,x:(r7+$0d)
        move    r7,r4
        move    #>$40,n4
        move    (r4)+n4
        move    #>$200000,x0
        move    x0,x:(r4)+
        move    #>$200000,x0
        move    x0,x:(r4)+
        move    #>$200000,x0
        move    x0,x:(r4)+
        move    #>$400000,x0
        move    x0,x:(r4)+
        move    #>$200000,x0
        move    x0,x:(r4)+
        move    #>$400000,x0
        move    x0,x:(r4)+
        move    #>$2ff222,x0
        move    x0,x:(r4)+
        move    #>$400000,x0
        move    x0,x:(r4)+
        move    #>$5fe443,x0
        move    x0,x:(r4)+
        move    #>$285146,x0
        move    x0,x:(r4)+
        move    #>$2ff222,x0
        move    x0,x:(r4)+
        move    #>$400000,x0
        move    x0,x:(r4)+
        move    #>$260dfc,x0
        move    x0,x:(r4)+
        move    #>$2ff222,x0
        move    x0,x:(r4)+
        move    #>$400000,x0
        move    x0,x:(r4)+
        move    #>$285146,x0
        move    x0,x:(r4)+
        move    #>$2ff222,x0
        move    x0,x:(r4)+
        move    #>$3c6870,x0
        move    x0,x:(r4)+
        move    #>$260dfc,x0
        move    x0,x:(r4)+
        move    #>$2ff222,x0
        move    x0,x:(r4)+
        move    #>$39047c,x0
        move    x0,x:(r4)+
        move    #>$2ab702,x0
        move    x0,x:(r4)+
        move    #>$2ff222,x0
        move    x0,x:(r4)+
        move    #>$400000,x0
        move    x0,x:(r4)+
        move    #>$000035,x0
        move    x0,x:(r4)+
        move    #>$000050,x0
        move    x0,x:(r4)+
        move    #>$000079,x0
        move    x0,x:(r4)+
        move    #>$0000b6,x0
        move    x0,x:(r4)+
        move    #>$000112,x0
        move    x0,x:(r4)+
        move    #>$00019d,x0
        move    x0,x:(r4)+
        move    #>$00026f,x0
        move    x0,x:(r4)+
        move    #>$0003aa,x0
        move    x0,x:(r4)+
        move    #>$000585,x0
        move    x0,x:(r4)+
        move    #>$000851,x0
        move    x0,x:(r4)+
        move    #>$000c87,x0
        move    x0,x:(r4)+
        move    #>$0012df,x0
        move    x0,x:(r4)+
        move    #>$001c6e,x0
        move    x0,x:(r4)+
        move    #>$002ad5,x0
        move    x0,x:(r4)+
        move    #>$004086,x0
        move    x0,x:(r4)+
        move    #>$006134,x0
        move    x0,x:(r4)+
        rts

proc:
        move    x:(r7+$01),a
        move    #>$004000,x0
        cmp     x0,a
        blt     wv01
        move    x:(r6),a
        and     #>$7f0000,a
        move    a1,x0
        move    #>$70e1c4,y1
        mpy     x0,y1,a                     ; FRAM -> frames 0..7, /8
        move    a,x:(r7+$29)
        move    x:(r6+$1),a
        and     #>$7f0000,a
        move    a1,x:(r7+$2a)
        move    x:(r6+$2),a
        and     #>$7f0000,a
        move    a1,x0
        move    #>$7954f8,y1
        mpy     x0,y1,a                     ; RES: setMasterResonance x .95
        move    a,x:(r7+$2b)
        move    x:(r6+$5),a
        and     #>$7f0000,a
        move    a1,x:(r7+$30)
        move    x:(r6+$c),a
        and     #>$ff0000,a
        move    a1,x:(r7+$2c)
        move    x:(r6+$c),a
        and     #>$00ff00,a
        asr     #$8,a,a
        move    r7,b
        add     #>$000058,b
        add     a,b
        move    b1,r4
        nop
        move    x:(r4),a
        move    a,x:(r7+$2d)
        move    x:(r6+$d),a
        and     #>$ff0000,a
        move    a1,x:(r7+$2e)
        move    x:(r6+$d),a
        and     #>$00ff00,a
        asr     #$8,a,a
        move    r7,b
        add     #>$000058,b
        add     a,b
        move    b1,r4
        nop
        move    x:(r4),a
        move    a,x:(r7+$2f)
        move    x:(r7+$0f),a
        move    x:(r6+$4),b
        and     #>$7f0000,b                 ; the companion byte is not the knob
        asr     #$10,b,b                    ; OCT, b0 clean
        move    #>$000004,x0
        cmp     x0,b
        tgt     x0,b                        ; OCT clamped to 0..4
        sub     x0,b
        neg     b                           ; octaves down
        move    b1,n3
        tst     b
        beq     wv11
        do      n3,>wv11
        asr     #$1,a,a
wv11:
        move    a,x:(r7+$3a)                 ; root increment
        move    x:(r6+$3),a
        and     #>$7f0000,a
        asr     #$10,a,a
        move    a,b
        asl     #$1,a,a
        add     b,a
        move    r7,b
        add     #>$000040,b
        add     a,b
        move    b1,r4
        move    x:(r6+$e),a
        and     #>$ff0000,a
        move    a1,x1                       ; DETN
        move    x:(r7+$3a),x0
        move    x0,a
        move    #>$fb81d8,y1
        move    x1,b
        move    b,x0
        mpy     x0,y1,b
        move    b,y1
        move    x:(r7+$3a),x0
        mac     x0,y1,a                     ; x (1 + spread)
        move    a,x:(r7+$25)
        move    x:(r7+$3a),x0
        move    x:(r4)+,y1
        mpy     x0,y1,a
        asl     #$2,a,a                     ; root x 2^(s/12)
        move    a,x0
        move    #>$fe809d,y1
        move    x1,b
        move    b,x0
        mpy     x0,y1,b
        move    b,y1
        move    a,x0
        mac     x0,y1,a                     ; x (1 + spread)
        move    a,x:(r7+$26)
        move    x:(r7+$3a),x0
        move    x:(r4)+,y1
        mpy     x0,y1,a
        asl     #$2,a,a                     ; root x 2^(s/12)
        move    a,x0
        move    #>$017f63,y1
        move    x1,b
        move    b,x0
        mpy     x0,y1,b
        move    b,y1
        move    a,x0
        mac     x0,y1,a                     ; x (1 + spread)
        move    a,x:(r7+$27)
        move    x:(r7+$3a),x0
        move    x:(r4)+,y1
        mpy     x0,y1,a
        asl     #$2,a,a                     ; root x 2^(s/12)
        move    a,x0
        move    #>$047e28,y1
        move    x1,b
        move    b,x0
        mpy     x0,y1,b
        move    b,y1
        move    a,x0
        mac     x0,y1,a                     ; x (1 + spread)
        move    a,x:(r7+$28)
        move    #>$0007ff,m2
        move    #>$0007ff,m3
        move    #>$000001,n0
        do      n7,>wv98
        move    x:(r0),a
        move    x:(r0+n0),x0
        add     x0,a
        asr     #$2,a,a                     ; mono, halved again for the crossing arithmetic
        move    a,x1
        abs     a
        move    x:(r7+$0a),b
        sub     b,a
        asr     #$7,a,a
        add     b,a
        move    a,x:(r7+$0a)
        move    x:(r7+$0b),b
        sub     b,a
        asr     #$7,a,a
        add     b,a
        move    a,x:(r7+$0b)
        move    x:(r7+$0d),a
        add     #>$000001,a
        move    #>$001000,x0
        cmp     x0,a
        ble     wv12
        move    x0,a
wv12:
        move    a,x:(r7+$0d)
        move    x:(r7+$0c),a
        tst     a
        bge     wv13
        move    x1,b
        tst     b
        blt     wv13
        move    x:(r7+$0b),a
        move    #>$001000,x0
        cmp     x0,a
        blt     wv13
        move    x1,x:(r7+$37)                  ; this sample, while x1 is in use
        move    x:(r7+$0c),a
        neg     a                           ; num = -prev
        move    x:(r7+$37),b
        move    x:(r7+$0c),x0
        sub     x0,b                        ; den = cur - prev >= num
        move    #>$400000,x0
        do      #$17,>wv16                 ; normalise: at most 23 doublings
        cmp     x0,b
        bge     wv15
        asl     #$1,b,b
        asl     #$1,a,a
wv15:
        nop
        nop
wv16:
        move    a,x:(r7+$33)
        move    b,x:(r7+$39)                  ; xn
        move    b,x1
        move    #>$5d4120,a
        asl     #$1,a,a
        sub     x1,a                        ; the seed, 1.4571 - xn
        move    a,y1
        move    x:(r7+$39),x0
        mpy     x0,y1,b                     ; xn y/2
        move    #>$400000,a
        sub     b,a
        add     #>$400000,a                 ; 1 - xn y/2
        move    a,x0
        mpy     x0,y1,a
        asl     #$1,a,a
        move    a,y1
        move    x:(r7+$39),x0
        mpy     x0,y1,b                     ; xn y/2
        move    #>$400000,a
        sub     b,a
        add     #>$400000,a                 ; 1 - xn y/2
        move    a,x0
        mpy     x0,y1,a
        asl     #$1,a,a
        move    a,y1
        move    x:(r7+$39),x0
        mpy     x0,y1,b                     ; xn y/2
        move    #>$400000,a
        sub     b,a
        add     #>$400000,a                 ; 1 - xn y/2
        move    a,x0
        mpy     x0,y1,a
        asl     #$1,a,a
        move    a,y1
        move    x:(r7+$33),x0
        mpy     x0,y1,a
        asl     #$1,a,a                     ; f = num / den (1.0 saturates)
        move    a,x0
        move    x:(r7+$0d),a
        asl     #$8,a,a                     ; CNT x 256
        move    x0,b
        asr     #$f,b,b
        add     b,a
        move    x:(r7+$0e),b
        asr     #$f,b,b
        sub     b,a                         ; T x 256
        move    x0,x:(r7+$0e)
        move    x:(r7+$0d),b
        move    #>$001000,x0
        cmp     x0,b
        bge     wv14
        move    #>$000200,x0
        cmp     x0,a
        ble     wv14
        move    a,b
        move    #>$000001,a                 ; 2^-23, doubled with the normalisation
        move    #>$400000,x0
        do      #$17,>wv18                 ; normalise: at most 23 doublings
        cmp     x0,b
        bge     wv17
        asl     #$1,b,b
        asl     #$1,a,a
wv17:
        nop
        nop
wv18:
        move    a,x:(r7+$3a)
        move    b,x:(r7+$39)                  ; xn
        move    b,x1
        move    #>$5d4120,a
        asl     #$1,a,a
        sub     x1,a                        ; the seed, 1.4571 - xn
        move    a,y1
        move    x:(r7+$39),x0
        mpy     x0,y1,b                     ; xn y/2
        move    #>$400000,a
        sub     b,a
        add     #>$400000,a                 ; 1 - xn y/2
        move    a,x0
        mpy     x0,y1,a
        asl     #$1,a,a
        move    a,y1
        move    x:(r7+$39),x0
        mpy     x0,y1,b                     ; xn y/2
        move    #>$400000,a
        sub     b,a
        add     #>$400000,a                 ; 1 - xn y/2
        move    a,x0
        mpy     x0,y1,a
        asl     #$1,a,a
        move    a,y1
        move    x:(r7+$39),x0
        mpy     x0,y1,b                     ; xn y/2
        move    #>$400000,a
        sub     b,a
        add     #>$400000,a                 ; 1 - xn y/2
        move    a,x0
        mpy     x0,y1,a
        asl     #$1,a,a
        move    a,y1
        move    x:(r7+$3a),x0
        mpy     x0,y1,a
        asl     #$a,a,a                     ; inc = 2^32 / (T x 256)
        move    a,x:(r7+$0f)
wv14:
        clr     a
        move    a,x:(r7+$0d)
        move    x:(r7+$37),x1
wv13:
        move    x1,x:(r7+$0c)
        move    x:(r7+$04),a
        move    x:(r7+$2d),x0
        add     x0,a
        move    a1,x:(r7+$04)
        move    x:(r7+$04),a
        add     #>$800000,a
        move    a1,x0
        move    x0,a
        abs     a
        sub     #>$400000,a
        asl     #$1,a,a
        move    a,x0
        move    x:(r7+$2c),y1
        mpy     x0,y1,a
        move    x:(r7+$2a),x0
        add     x0,a                        ; c = cutoff + LFO
        move    a,b
        asl     #$1,b,b
        add     #>$0147ae,b
        tst     b
        bge     wv19
        clr     b
wv19:
        move    #>$7d70a4,x0
        cmp     x0,b
        ble     wv20
        move    x0,b
wv20:
        move    b,x0
        move    b,y1
        mpy     x0,y1,b
        move    b,x0
        mpy     x0,y1,b                     ; lp target, (.01 + 2c)^3
        move    a,x0
        move    #>$79999a,y1
        mpy     x0,y1,a
        asl     #$1,a,a
        sub     #>$400000,a
        sub     #>$400000,a                 ; 1.9c - 1
        tst     a
        bge     wv21
        clr     a
wv21:
        move    #>$733333,x0
        cmp     x0,a
        ble     wv22
        move    x0,a
wv22:
        move    a,x0
        move    a,y1
        mpy     x0,y1,a
        move    a,x0
        mpy     x0,y1,a                     ; hp target
        move    #>$00068e,y1
        move    x:(r7+$05),x0
        sub     x0,b
        move    b,x0
        mpy     x0,y1,b
        move    x:(r7+$05),x0
        add     x0,b
        move    b,x:(r7+$05)                 ; fonepole .0002
        move    x:(r7+$06),x0
        sub     x0,a
        move    a,x0
        mpy     x0,y1,a
        move    x:(r7+$06),x0
        add     x0,a
        move    a,x:(r7+$06)                 ; fonepole .0002
        move    #>$7fffff,a
        move    x:(r7+$05),x0
        sub     x0,a
        move    a,x0
        move    x:(r7+$07),y1
        mpy     x0,y1,b
        move    #>$040000,a
        sub     b,a
        move    a,x0
        mpy     x0,y1,a
        asl     #$5,a,a
        add     y1,a
        move    a,x:(r7+$07)                 ; Newton: 1/(1-f), /32
        move    a,y1
        move    x:(r7+$2b),x0
        mpy     x0,y1,a
        move    x0,b
        asr     #$5,b,b
        add     b,a
        move    a,x:(r7+$31)                 ; feedback /32: res + res/(1-f)
        move    #>$7fffff,a
        move    x:(r7+$06),x0
        sub     x0,a
        move    a,x0
        move    x:(r7+$08),y1
        mpy     x0,y1,b
        move    #>$040000,a
        sub     b,a
        move    a,x0
        mpy     x0,y1,a
        asl     #$5,a,a
        add     y1,a
        move    a,x:(r7+$08)                 ; Newton: 1/(1-f), /32
        move    a,y1
        move    x:(r7+$2b),x0
        mpy     x0,y1,a
        move    x0,b
        asr     #$5,b,b
        add     b,a
        move    a,x:(r7+$32)                 ; feedback /32: res + res/(1-f)
        move    x:(r7+$29),a
        move    x:(r7+$09),b
        sub     b,a
        asr     #$8,a,a
        add     b,a
        move    a,x:(r7+$09)
        move    a,b
        and     #>$0fffff,b
        asl     #$3,b,b
        move    b1,x0
        move    x0,x:(r7+$34)
        asr     #$14,a,a
        asl     #$b,a,a
        move    x:(r7+$00),x0
        add     x0,a
        move    a1,x:(r7+$35)
        add     #>$000800,a
        move    a1,x:(r7+$36)
        move    x:(r7+$10),a
        move    x:(r7+$2f),x0
        add     x0,a
        move    a1,x:(r7+$10)
        move    x:(r7+$10),a
        add     #>$800000,a
        move    a1,x0
        move    x0,a
        abs     a
        sub     #>$400000,a
        asl     #$1,a,a
        move    a,x0
        move    x:(r7+$2e),y1
        mpy     x0,y1,a
        move    a,x0
        move    #>$0ec982,y1
        mpy     x0,y1,a
        move    a,x0
        move    a,y1
        mpy     x0,y1,b
        asr     #$2,b,b
        asr     #$1,a,a
        add     b,a
        add     #>$400000,a
        move    a,x:(r7+$38)
        move    x:(r7+$0b),x0
        move    #>$0595c6,y1
        mpy     x0,y1,a
        move    a,x:(r7+$33)
        clr     a
        move    a,x:(r7+$37)
        move    x:(r7+$0b),a
        tst     a
        beq     wv23
; voice 0
        move    x:(r7+$11),a
        lsr     #$d,a
        move    a1,n2
        move    a1,n3
        move    x:(r7+$11),b
        and     #>$001fff,b
        asl     #$a,b,b
        move    b1,y1                       ; frac
        move    x:(r7+$35),r2
        move    (r2)+n2
        move    y:(r2)+,b
        move    y:(r2),x0
        move    x0,a
        sub     b,a
        move    a,x0
        mac     x0,y1,b                     ; frame A
        move    b,y0
        move    x:(r7+$36),r3
        move    (r3)+n3
        move    y:(r3)+,b
        move    y:(r3),x0
        move    x0,a
        sub     b,a
        move    a,x0
        mac     x0,y1,b                     ; frame B
        move    y0,a
        sub     a,b
        move    b,x0
        move    x:(r7+$34),y1
        mac     x0,y1,a                     ; A + morph (B - A)
        move    a,x0
        move    x:(r7+$33),y1
        mpy     x0,y1,a                     ; x envelope
        move    a,x1
        move    x:(r7+$12),a
        move    x:(r7+$13),x0
        sub     x0,a
        move    a,x0
        move    x:(r7+$31),y1
        mpy     x0,y1,b
        asl     #$5,b,b
        add     x1,b
        move    x:(r7+$12),x0
        sub     x0,b
        move    b,x0
        move    x:(r7+$05),y1
        move    x:(r7+$12),a
        mac     x0,y1,a
        move    a,x:(r7+$12)
        move    x:(r7+$13),b
        sub     b,a
        move    a,x0
        mac     x0,y1,b
        move    b,x:(r7+$13)
        move    b,x1
        move    x:(r7+$14),a
        move    x:(r7+$15),x0
        sub     x0,a
        move    a,x0
        move    x:(r7+$32),y1
        mpy     x0,y1,b
        asl     #$5,b,b
        add     x1,b
        move    x:(r7+$14),x0
        sub     x0,b
        move    b,x0
        move    x:(r7+$06),y1
        move    x:(r7+$14),a
        mac     x0,y1,a
        move    a,x:(r7+$14)
        move    x:(r7+$15),b
        sub     b,a
        move    a,x0
        mac     x0,y1,b
        move    b,x:(r7+$15)
        move    x1,b
        move    x:(r7+$14),x0
        sub     x0,b
        move    x:(r7+$37),x0
        add     x0,b
        move    b,x:(r7+$37)
        move    x:(r7+$25),x0
        move    x:(r7+$38),y1
        mpy     x0,y1,b
        asl     #$1,b,b
        move    b1,x0
        move    x:(r7+$11),a
        add     x0,a
        move    a1,x:(r7+$11)
; voice 1
        move    x:(r7+$16),a
        lsr     #$d,a
        move    a1,n2
        move    a1,n3
        move    x:(r7+$16),b
        and     #>$001fff,b
        asl     #$a,b,b
        move    b1,y1                       ; frac
        move    x:(r7+$35),r2
        move    (r2)+n2
        move    y:(r2)+,b
        move    y:(r2),x0
        move    x0,a
        sub     b,a
        move    a,x0
        mac     x0,y1,b                     ; frame A
        move    b,y0
        move    x:(r7+$36),r3
        move    (r3)+n3
        move    y:(r3)+,b
        move    y:(r3),x0
        move    x0,a
        sub     b,a
        move    a,x0
        mac     x0,y1,b                     ; frame B
        move    y0,a
        sub     a,b
        move    b,x0
        move    x:(r7+$34),y1
        mac     x0,y1,a                     ; A + morph (B - A)
        move    a,x0
        move    x:(r7+$33),y1
        mpy     x0,y1,a                     ; x envelope
        move    a,x1
        move    x:(r7+$17),a
        move    x:(r7+$18),x0
        sub     x0,a
        move    a,x0
        move    x:(r7+$31),y1
        mpy     x0,y1,b
        asl     #$5,b,b
        add     x1,b
        move    x:(r7+$17),x0
        sub     x0,b
        move    b,x0
        move    x:(r7+$05),y1
        move    x:(r7+$17),a
        mac     x0,y1,a
        move    a,x:(r7+$17)
        move    x:(r7+$18),b
        sub     b,a
        move    a,x0
        mac     x0,y1,b
        move    b,x:(r7+$18)
        move    b,x1
        move    x:(r7+$19),a
        move    x:(r7+$1a),x0
        sub     x0,a
        move    a,x0
        move    x:(r7+$32),y1
        mpy     x0,y1,b
        asl     #$5,b,b
        add     x1,b
        move    x:(r7+$19),x0
        sub     x0,b
        move    b,x0
        move    x:(r7+$06),y1
        move    x:(r7+$19),a
        mac     x0,y1,a
        move    a,x:(r7+$19)
        move    x:(r7+$1a),b
        sub     b,a
        move    a,x0
        mac     x0,y1,b
        move    b,x:(r7+$1a)
        move    x1,b
        move    x:(r7+$19),x0
        sub     x0,b
        move    x:(r7+$37),x0
        add     x0,b
        move    b,x:(r7+$37)
        move    x:(r7+$26),x0
        move    x:(r7+$38),y1
        mpy     x0,y1,b
        asl     #$1,b,b
        move    b1,x0
        move    x:(r7+$16),a
        add     x0,a
        move    a1,x:(r7+$16)
; voice 2
        move    x:(r7+$1b),a
        lsr     #$d,a
        move    a1,n2
        move    a1,n3
        move    x:(r7+$1b),b
        and     #>$001fff,b
        asl     #$a,b,b
        move    b1,y1                       ; frac
        move    x:(r7+$35),r2
        move    (r2)+n2
        move    y:(r2)+,b
        move    y:(r2),x0
        move    x0,a
        sub     b,a
        move    a,x0
        mac     x0,y1,b                     ; frame A
        move    b,y0
        move    x:(r7+$36),r3
        move    (r3)+n3
        move    y:(r3)+,b
        move    y:(r3),x0
        move    x0,a
        sub     b,a
        move    a,x0
        mac     x0,y1,b                     ; frame B
        move    y0,a
        sub     a,b
        move    b,x0
        move    x:(r7+$34),y1
        mac     x0,y1,a                     ; A + morph (B - A)
        move    a,x0
        move    x:(r7+$33),y1
        mpy     x0,y1,a                     ; x envelope
        move    a,x1
        move    x:(r7+$1c),a
        move    x:(r7+$1d),x0
        sub     x0,a
        move    a,x0
        move    x:(r7+$31),y1
        mpy     x0,y1,b
        asl     #$5,b,b
        add     x1,b
        move    x:(r7+$1c),x0
        sub     x0,b
        move    b,x0
        move    x:(r7+$05),y1
        move    x:(r7+$1c),a
        mac     x0,y1,a
        move    a,x:(r7+$1c)
        move    x:(r7+$1d),b
        sub     b,a
        move    a,x0
        mac     x0,y1,b
        move    b,x:(r7+$1d)
        move    b,x1
        move    x:(r7+$1e),a
        move    x:(r7+$1f),x0
        sub     x0,a
        move    a,x0
        move    x:(r7+$32),y1
        mpy     x0,y1,b
        asl     #$5,b,b
        add     x1,b
        move    x:(r7+$1e),x0
        sub     x0,b
        move    b,x0
        move    x:(r7+$06),y1
        move    x:(r7+$1e),a
        mac     x0,y1,a
        move    a,x:(r7+$1e)
        move    x:(r7+$1f),b
        sub     b,a
        move    a,x0
        mac     x0,y1,b
        move    b,x:(r7+$1f)
        move    x1,b
        move    x:(r7+$1e),x0
        sub     x0,b
        move    x:(r7+$37),x0
        add     x0,b
        move    b,x:(r7+$37)
        move    x:(r7+$27),x0
        move    x:(r7+$38),y1
        mpy     x0,y1,b
        asl     #$1,b,b
        move    b1,x0
        move    x:(r7+$1b),a
        add     x0,a
        move    a1,x:(r7+$1b)
; voice 3
        move    x:(r7+$20),a
        lsr     #$d,a
        move    a1,n2
        move    a1,n3
        move    x:(r7+$20),b
        and     #>$001fff,b
        asl     #$a,b,b
        move    b1,y1                       ; frac
        move    x:(r7+$35),r2
        move    (r2)+n2
        move    y:(r2)+,b
        move    y:(r2),x0
        move    x0,a
        sub     b,a
        move    a,x0
        mac     x0,y1,b                     ; frame A
        move    b,y0
        move    x:(r7+$36),r3
        move    (r3)+n3
        move    y:(r3)+,b
        move    y:(r3),x0
        move    x0,a
        sub     b,a
        move    a,x0
        mac     x0,y1,b                     ; frame B
        move    y0,a
        sub     a,b
        move    b,x0
        move    x:(r7+$34),y1
        mac     x0,y1,a                     ; A + morph (B - A)
        move    a,x0
        move    x:(r7+$33),y1
        mpy     x0,y1,a                     ; x envelope
        move    a,x1
        move    x:(r7+$21),a
        move    x:(r7+$22),x0
        sub     x0,a
        move    a,x0
        move    x:(r7+$31),y1
        mpy     x0,y1,b
        asl     #$5,b,b
        add     x1,b
        move    x:(r7+$21),x0
        sub     x0,b
        move    b,x0
        move    x:(r7+$05),y1
        move    x:(r7+$21),a
        mac     x0,y1,a
        move    a,x:(r7+$21)
        move    x:(r7+$22),b
        sub     b,a
        move    a,x0
        mac     x0,y1,b
        move    b,x:(r7+$22)
        move    b,x1
        move    x:(r7+$23),a
        move    x:(r7+$24),x0
        sub     x0,a
        move    a,x0
        move    x:(r7+$32),y1
        mpy     x0,y1,b
        asl     #$5,b,b
        add     x1,b
        move    x:(r7+$23),x0
        sub     x0,b
        move    b,x0
        move    x:(r7+$06),y1
        move    x:(r7+$23),a
        mac     x0,y1,a
        move    a,x:(r7+$23)
        move    x:(r7+$24),b
        sub     b,a
        move    a,x0
        mac     x0,y1,b
        move    b,x:(r7+$24)
        move    x1,b
        move    x:(r7+$23),x0
        sub     x0,b
        move    x:(r7+$37),x0
        add     x0,b
        move    b,x:(r7+$37)
        move    x:(r7+$28),x0
        move    x:(r7+$38),y1
        mpy     x0,y1,b
        asl     #$1,b,b
        move    b1,x0
        move    x:(r7+$20),a
        add     x0,a
        move    a1,x:(r7+$20)
        move    x:(r7+$37),x0
        move    x:(r7+$30),y1
        mpy     x0,y1,a
        asl     #$4,a,a                     ; x 8 at LEVL 64
        move    a,x:(r0)+
        move    a,x:(r0)+
        move    x:(r7+$0b),a
        tst     a
        bne     wv24                       ; sounding: past the silence path
wv23:
        clr     a
        move    a,x:(r7+$12)
        move    a,x:(r7+$13)
        move    a,x:(r7+$14)
        move    a,x:(r7+$15)
        move    a,x:(r7+$17)
        move    a,x:(r7+$18)
        move    a,x:(r7+$19)
        move    a,x:(r7+$1a)
        move    a,x:(r7+$1c)
        move    a,x:(r7+$1d)
        move    a,x:(r7+$1e)
        move    a,x:(r7+$1f)
        move    a,x:(r7+$21)
        move    a,x:(r7+$22)
        move    a,x:(r7+$23)
        move    a,x:(r7+$24)
        move    a,x:(r0)+
        move    a,x:(r0)+
wv24:
        nop
wv98:
        nop
        move    #>$ffffff,m2
        move    #>$ffffff,m3
        rts

wv01:
        move    x:(r7+$00),a
        move    x:(r7+$01),x0
        add     x0,a
        move    a1,r4
        move    #>$ffffff,m4
        move    x:(r7+$01),a
        asr     #$b,a,a                     ; frame
        move    a1,n4
        move    n4,a
        move    #>$000001,x0
        cmp     x0,a
        beq     wv26
        move    n4,a
        move    #>$000002,x0
        cmp     x0,a
        beq     wv27
        move    n4,a
        move    #>$000003,x0
        cmp     x0,a
        beq     wv28
        move    n4,a
        move    #>$000004,x0
        cmp     x0,a
        beq     wv29
        move    n4,a
        move    #>$000005,x0
        cmp     x0,a
        beq     wv30
        move    n4,a
        move    #>$000006,x0
        cmp     x0,a
        beq     wv31
        move    n4,a
        move    #>$000007,x0
        cmp     x0,a
        beq     wv32
wv25:
        move    #>$006488,y1
        do      #$100,>wv33
        move    x:(r7+$02),a
        move    a,y:(r4)+
        move    x:(r7+$03),x0
        mac     x0,y1,a
        move    a,x:(r7+$02)
        move    a,x0
        move    x:(r7+$03),b
        mac     -x0,y1,b
        move    b,x:(r7+$03)
wv33:
        nop
        bra     wv02
wv26:
        move    x:(r7+$01),a
        and     #>$0007ff,a
        move    a1,r5
        do      #$100,>wv37
        move    r5,a                        ; i
        move    #>$000200,x0
        cmp     x0,a
        blt     wv34
        move    #>$000600,x0
        cmp     x0,a
        blt     wv35
        sub     #>$000800,a
        bra     wv34
wv35:
        move    a,x0
        move    #>$000400,a
        sub     x0,a
wv34:
        asl     #$d,a,a                     ; t / 1024: half scale
        move    a,x0
        move    #>$733333,y1
        mpy     x0,y1,a
        move    a,y:(r4)+
        move    (r5)+
wv37:
        nop
        bra     wv02
wv27:
        move    x:(r7+$01),a
        and     #>$0007ff,a
        move    a1,r5
        do      #$100,>wv39
        move    r5,a                        ; i
        move    #>$000400,x0
        cmp     x0,a
        blt     wv38
        sub     #>$000800,a
wv38:
        asl     #$c,a,a                     ; t / 2048: half scale
        move    a,x0
        move    #>$733333,y1
        mpy     x0,y1,a
        move    a,y:(r4)+
        move    (r5)+
wv39:
        nop
        bra     wv02
wv28:
        move    x:(r7+$01),a
        and     #>$0007ff,a
        move    a1,r5
        do      #$100,>wv42
        move    r5,a                        ; i
        move    #>$000400,x0
        cmp     x0,a
        blt     wv40
        move    #>$c66666,a
        bra     wv41
wv40:
        move    #>$39999a,a
wv41:
        move    a,y:(r4)+
        move    (r5)+
wv42:
        nop
        bra     wv02
wv29:
        move    x:(r7+$01),a
        and     #>$0007ff,a
        move    a1,r5
        do      #$100,>wv45
        move    r5,a                        ; i
        move    #>$000200,x0
        cmp     x0,a
        blt     wv43
        move    #>$eccccd,a
        bra     wv44
wv43:
        move    #>$39999a,a
wv44:
        move    a,y:(r4)+
        move    (r5)+
wv45:
        nop
        bra     wv02
wv30:
        move    x:(r7+$01),a
        and     #>$0007ff,a
        move    a1,r5
        do      #$100,>wv48
        move    r5,a                        ; i
        move    #>$000100,x0
        cmp     x0,a
        blt     wv46
        move    #>$f7c57c,a
        bra     wv47
wv46:
        move    #>$39999a,a
wv47:
        move    a,y:(r4)+
        move    (r5)+
wv48:
        nop
        bra     wv02
wv31:
        move    x:(r7+$01),a
        and     #>$0007ff,a
        move    a1,r5
        do      #$100,>wv51
        move    r5,a                        ; i
        move    #>$000080,x0
        cmp     x0,a
        blt     wv49
        move    #>$fc28f6,a
        bra     wv50
wv49:
        move    #>$39999a,a
wv50:
        move    a,y:(r4)+
        move    (r5)+
wv51:
        nop
        bra     wv02
wv32:
        move    x:(r7+$01),a
        and     #>$0007ff,a
        move    a1,r5
        do      #$100,>wv54
        move    r5,a                        ; i
        move    #>$000040,x0
        cmp     x0,a
        blt     wv52
        move    #>$fe2456,a
        bra     wv53
wv52:
        move    #>$39999a,a
wv53:
        move    a,y:(r4)+
        move    (r5)+
wv54:
        nop
        bra     wv02
wv02:
        move    x:(r7+$01),a
        add     #>$000100,a
        move    a,x:(r7+$01)
        clr     a
        do      n7,>wv55
        move    a,x:(r0)+
        move    a,x:(r0)+
wv55:
        nop
        rts

