#!/usr/bin/env python3
"""Audit generated ColdFire Perky assembly before firmware linking.

This is deliberately independent of the PCM/source qualification. It examines
the actual m68k-elf-gcc assembly and, when the cross binutils are available,
assembles every unit and verifies that all undefined symbols are either resolved
by another generated Perky unit or belong to the tiny intentional stock/asset
interface.
"""
from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

UNITS = ("pkcontrol.s", "pkcore.s", "pkfold.s", "pkkarplus.s", "pknoise.s",
         "pksimpledrum.s", "pkcomplexdrum.s", "pkslap.s", "pkwavetable.s",
         "pkah.s")
RUNTIME = re.compile(r"\b__[A-Za-z_][A-Za-z0-9_]*\b")
LIBC = re.compile(r"\b(?:memcpy|memmove|memset|memcmp|strlen|abort|malloc|free)\b")
FLOAT_OP = re.compile(
    r"^(?:f(?:add|sub|mul|div|move|cmp|sqrt|neg|abs|int|intrz|scale|mod|rem|sin|cos|tan|log|exp)[a-z0-9.]*)$",
    re.I,
)
CALL_OP = re.compile(r"^(?:jsr|jbsr|bsr(?:\.[bwl])?)$", re.I)
MULDIV_OP = re.compile(r"^(?:muls?|mulu|divs?|divu)(?:\.[bwl])?$", re.I)

ALLOWED_UNDEFINED = {
    "pk_stock_validate",
    "pk_stock_pool_open",
    "pk_asset_pitch",
    "pk_asset_chromatic",
    "pk_asset_envelope1",
    "pk_asset_envelope2",
    "pk_asset_m1_wave",
    "pk_asset_wave0",
    "pk_asset_wave1",
    "pk_asset_wave2",
    "pk_asset_wave3",
    "pk_asset_wt_base",
    "pk_asset_wt_bank",
    "pk_asset_ah_closed",
    "pk_asset_ah_open",
    "pk_asset_ah_ride",
}


def fail(msg: str) -> "NoReturn":
    raise SystemExit("PERKY CF codegen audit: FAIL: " + msg)


def assembly_stats(path: Path) -> tuple[int, int, int]:
    text = path.read_text(errors="strict")
    if "Generated by generate_cf_final.py with m68k-elf-gcc" not in text:
        fail(f"{path.name}: missing generator/compiler provenance header")
    bad_runtime = sorted(set(RUNTIME.findall(text)))
    if bad_runtime:
        fail(f"{path.name}: compiler/runtime helper(s): {', '.join(bad_runtime)}")
    bad_libc = sorted(set(LIBC.findall(text)))
    if bad_libc:
        fail(f"{path.name}: libc helper(s): {', '.join(bad_libc)}")

    instructions = calls = muldiv = 0
    for raw in text.splitlines():
        line = raw.split("|", 1)[0].strip()
        if not line or line.endswith(":") or line.startswith("."):
            continue
        token = line.split(None, 1)[0]
        if not re.match(r"^[A-Za-z][A-Za-z0-9.]*$", token):
            continue
        instructions += 1
        if FLOAT_OP.match(token):
            fail(f"{path.name}: floating-point opcode emitted: {token}")
        if CALL_OP.match(token):
            calls += 1
        if MULDIV_OP.match(token):
            muldiv += 1
    if instructions == 0:
        fail(f"{path.name}: no instructions found")
    return instructions, calls, muldiv


def nm_symbols(nm: str, obj: Path, *args: str) -> set[str]:
    p = subprocess.run([nm, *args, str(obj)], check=True, capture_output=True, text=True)
    out: set[str] = set()
    for line in p.stdout.splitlines():
        fields = line.split()
        if fields:
            out.add(fields[-1])
    return out


def object_linkage_audit(generated: Path) -> None:
    gcc = shutil.which("m68k-elf-gcc")
    nm = shutil.which("m68k-elf-nm")
    if not gcc or not nm:
        print("PERKY CF codegen linkage: SKIP (m68k-elf-gcc/nm not installed)")
        return

    with tempfile.TemporaryDirectory(prefix="perky-cf-codegen-") as td:
        tdir = Path(td)
        objects: list[Path] = []
        for name in UNITS:
            src = generated / name
            obj = tdir / (src.stem + ".o")
            subprocess.run(
                [gcc, "-mcpu=54455", "-msoft-float", "-ffreestanding", "-c", str(src), "-o", str(obj)],
                check=True,
            )
            objects.append(obj)

        defined: set[str] = set()
        undefined: set[str] = set()
        for obj in objects:
            defined |= nm_symbols(nm, obj, "-g", "--defined-only")
            undefined |= nm_symbols(nm, obj, "-u")
        unresolved = sorted(undefined - defined - ALLOWED_UNDEFINED)
        if unresolved:
            fail("unexpected unresolved symbol(s): " + ", ".join(unresolved))
        print(
            "PERKY CF codegen linkage: PASS "
            f"({len(objects)} objects; unresolved interface="
            f"{','.join(sorted(undefined - defined)) or 'none'})"
        )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("generated", type=Path, help="directory containing generated pk*.s units")
    args = ap.parse_args()
    generated = args.generated.resolve()
    if not generated.is_dir():
        fail(f"not a directory: {generated}")
    missing = [name for name in UNITS if not (generated / name).is_file()]
    if missing:
        fail("missing generated unit(s): " + ", ".join(missing))

    totals = [0, 0, 0]
    print("PERKY CF generated assembly footprint:")
    for name in UNITS:
        insn, calls, muldiv = assembly_stats(generated / name)
        totals[0] += insn
        totals[1] += calls
        totals[2] += muldiv
        print(f"  {name:<13} instructions={insn:5d} calls={calls:3d} mul/div={muldiv:3d}")
    print(
        f"  TOTAL         instructions={totals[0]:5d} calls={totals[1]:3d} mul/div={totals[2]:3d}"
    )
    object_linkage_audit(generated)
    print("PERKY CF codegen audit: PASS")


if __name__ == "__main__":
    main()
