#!/usr/bin/env python3
"""Regenerate modules/perky/cf_acoustic_hats_rate.inc.

Acoustic Hats' TUNE control sets the sample-playback increment at object +0xCC.
It is a sqrt-shaped curve (increment^2 is proportional to the pitch-table value
to within 4e-4) but no closed form -- `isqrt(pitch*A)>>B`, a floor or a rounded
one, nor a linear fit in sqrt(pitch) -- reproduces all of it, so it is pinned as
captured data over the complete 12-bit raw-pitch domain, exactly as Slap's
filter-coefficient curve is.

The data comes from the real firmware through the control sweep, not from a fit:

    work/capture_sweep.exe <firmware> work/ah_full_m1_n45.bin 11 0 full 45
    work/capture_sweep.exe <firmware> work/ah_full_m1_n63.bin 11 0 full

The first walks every 12-bit TUNE target with note 45 (the shipping note), so
the raw pitch index is exactly the settled prepared word and covers 0..4092 --
the same 4093 reachable values the object can hold.  The second, at the engine
default note 63, supplies the three values above it.
"""
from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
WIN, OFF = 0x6000, 0x2A80
OUT = ROOT / "modules/perky/cf_acoustic_hats_rate.inc"


def u16(buf, off):
    return buf[off] | (buf[off + 1] << 8)


def u32(buf, off):
    return u16(buf, off) | (u16(buf, off + 2) << 16)


def table(path: pathlib.Path) -> dict[int, int]:
    raw = path.read_bytes()
    out: dict[int, int] = {}
    for target in range(len(raw) // WIN):
        rec = raw[target * WIN + OFF: target * WIN + OFF + 0x10C]
        out.setdefault(u16(rec, 0xBA), u32(rec, 0xCC))
    return out


def main() -> None:
    low = table(ROOT / "work/ah_full_m1_n45.bin")
    high = table(ROOT / "work/ah_full_m1_n63.bin")
    values = []
    for index in range(4096):
        if index in low:
            values.append(low[index])
        elif index in high:
            values.append(high[index])
        else:
            raise SystemExit(f"no captured increment for raw pitch {index}")
    rows = [
        "/* Generated by tools/perky/acoustic_hats_rate_table.py from the "
        "SHA-pinned",
        " * PERKONS v1.2.1 control sweep; do not edit.  Indexed by the raw pitch",
        " * (object +0xBA), one 16-bit sample-playback increment each. */",
        "static const uint16_t ah_rate_table[4096] = {",
    ]
    for i in range(0, len(values), 12):
        rows.append("    " + ",".join(f"0x{v:04x}" for v in values[i:i + 12]) + ",")
    rows.append("};")
    OUT.write_text("\n".join(rows) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(values)} entries, {min(values)}..{max(values)})")


if __name__ == "__main__":
    main()
