#!/usr/bin/env python3
"""Compose qualified Simple Drum assets with the hardware-tested Noise/Tone profile.

Reads local extracted firmware assets; generated bytes stay under out/.
Noise/Tone's reachable shape-1 path is analytic. Keep its wave stream exactly.
Simple Drum uses direct waves/envelope and a control-rate second-delta pitch cache.
"""
from pathlib import Path
import argparse, hashlib, json, struct, sys
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'modules/perky'))
import fabricate_noise_tone_fixtures as fab
import build_noise_tone_payload as nb
import build_simple_drum_runtime_payload as qualified
import build_multi_synth_source as source
import simple_drum_tables as tables
import simple_drum_live as live

def build(assets: Path, out: Path):
    out.mkdir(parents=True,exist_ok=True)
    for name in qualified.SOURCE_SHA256:
        qualified.verify_source(assets/name)
    fab.emit_tables(out/'synthetic-source')
    nb.build(out/'synthetic-source',out/'noise-packed')
    initial=[int(x,16) for x in (out/'noise-packed/state_init.words').read_text().split()]
    assert len(initial)==236 and all(initial[i*58+2]==1 for i in range(4))
    pitch=struct.unpack('<4096H',(assets/'pitch.bin').read_bytes())
    env=struct.unpack('<2048H',(assets/'envelope1.bin').read_bytes())
    waves=[x for a in [0x080222a0,0x080226a0,0x080228a0] for x in struct.unpack('<256H',(assets/f'wave_{a:08x}.bin').read_bytes())]
    banks=[([int(x,16) for x in (out/'noise-packed/tables.words').read_text().split()][:683]),tables.pack_u16(waves),tables.pack_u16(env[:1024]),tables.pack_pitch_basis(pitch).words,[0]]
    ywords=[v for bank in banks for v in bank]
    assert [len(b) for b in banks]==[683,512,683,67,1] and len(ywords)==1946
    xwords=initial+[0]*6
    for name,values in [('tables',ywords),('state_init',xwords)]:
        (out/f'{name}.words').write_text('\n'.join(f'{v:06x}' for v in values)+'\n')
        (out/f'{name}.bin').write_bytes(nb.words24_bytes(values))
    digest=lambda name:hashlib.sha256((out/name).read_bytes()).hexdigest()
    layout={'schema':'perky-multi-dsp-tables-v1','total_words':len(ywords),'sha256':digest('tables.bin'),
            'x_init':{'base_word':0x3800,'words':len(xwords),'sha256':digest('state_init.bin')},
            'pitch_cache':{'base_word':0x3964,'words':17,'initial_tag':65535},
            'noise_shape':1,'noise_provenance':'PERKY2 synthetic hardware-tested profile',
            'source_sha256':qualified.SOURCE_SHA256,
            'banks':{'noise_waves':0x7a5,'simple_waves':0xa50,'simple_envelope':0xc50,'simple_pitch':0xefb}}
    (out/'layout.json').write_text(json.dumps(layout,indent=2)+'\n')
    code=source.generate(out/'noise-packed/layout.json')
    for name,tag,values in [('noise',10,initial[:58]),('simple',2,live.LiveSimpleDrum.fresh().voice.words+[0xffff]+[0]*23)]:
        code+=f'\npk_multi_{name}_init:\n move x:>$418,a\n lsr #$5,a\n move a1,n1\n move #>$38ee,r1\n move x:(r1+n1),b\n cmp #>${tag:x},b\n beq pkm_{name}_initialized\n move #>${tag:x},a\n move a1,x:(r1+n1)\n move r6,r1\n clr a\n do #>$3a,pkm_{name}_zero\n move a1,x:(r1)+\npkm_{name}_zero:\n nop\n'
        for i,v in enumerate(values):
            if v:code+=f' move #>${v:06x},a\n move a1,x:(r6+${i:x})\n'
        code+=f'pkm_{name}_initialized:\n rts\n'
    code=source.noise.force_long_local_jsr(code)
    path=out/'multi.asm';path.write_text(code)
    print(f'Mixed shipping payload: {source.noise.measure(code,path)} P words, {len(ywords)} Y words, 359 claimed X words')
    return layout

def main():
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument('assets',type=Path);ap.add_argument('--out',type=Path,default=ROOT/'out/perky/multi')
    args=ap.parse_args();build(args.assets,args.out)
if __name__=='__main__':main()
