#!/usr/bin/env python3
"""Run the local evidence chain required for the first HW4 Karplus audition.

Uses the existing all-engine ARM fixture corpus; no network/CI.  The corpus is
normally generated by qualify_fold2_trigger.py/capture_engine_fixtures.py from
the pinned v1.2.1 firmware and PerkyBits source.

Renderer, raw trigger/retrigger and mandatory control update are independent
operations in the original firmware.  All three must pass before Karplus can be
used as evidence for a hardware candidate; a renderer/trigger pass alone does
not qualify live controls.
"""
from pathlib import Path
import argparse
import os
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_FIRMWARE = Path.home() / 'Downloads/perkons_both_v1.2.1-0-gbcccfd0.img'
DEFAULT_SOURCE = Path.home() / 'Downloads/perkybits'
FIX = ROOT / 'out/perky/engine-fixtures'


def run(*args, env=None):
    cmd = [sys.executable, *map(str, args)]
    print('+ ' + ' '.join(cmd), flush=True)
    subprocess.run(cmd, cwd=ROOT, check=True, env=env)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--firmware', type=Path,
                    default=Path(os.environ.get('PERKONS_FIRMWARE', DEFAULT_FIRMWARE)))
    ap.add_argument('--source', type=Path,
                    default=Path(os.environ.get('PERKYBITS_ROOT', DEFAULT_SOURCE)))
    a = ap.parse_args()
    if not (FIX / 'manifest.json').exists():
        raise SystemExit(
            'Karplus qualifier needs out/perky/engine-fixtures; run '
            'tools/perky/qualify_fold2_trigger.py once without --reuse-fixtures first.'
        )
    if not a.firmware.expanduser().exists():
        raise SystemExit(f'missing firmware: {a.firmware.expanduser()}')
    if not (a.source.expanduser() / 'Source/PerkonsVoices.cpp').exists():
        raise SystemExit(f'missing PerkyBits source tree: {a.source.expanduser()}')

    run('tools/perky/analyze_karplus_trigger.py', '--fixtures', FIX)
    run('tools/verify/verify_perky_karplus_trigger_contract.py')
    run('tools/verify/verify_perky_karplus_trigger_exec.py')

    # This used to be absent from the current HW4 qualification chain even
    # though Karplus' trigger is immediately followed by update() in v1.2.1.
    # Recovered update arithmetic is checked against the complete captured ARM
    # object for first and active retriggers before renderer evidence is used.
    run('tools/verify/verify_perky_karplus_control_update.py',
        '--firmware', a.firmware.expanduser(), '--fixtures', FIX)

    env = os.environ.copy()
    env['PERKYBITS_SOURCE'] = str((a.source.expanduser() / 'Source').resolve())
    run('tools/verify/verify_perky_karplus_dsp_exec.py', '--firmware', a.firmware.expanduser(), env=env)
    print(
        '\nKarplus HW4 evidence chain: PASS '
        '(original ARM trigger/retrigger + mandatory control update + '
        'DSP trigger + exact renderer/ring/RNG).'
    )


if __name__ == '__main__':
    main()
