"""Finite IEEE754 operations required by the original Acoustic Hats filter.

DSP recipes preserve round-to-nearest/even at each separate M7 conversion,
multiply and add. No approximate fixed-point substitute. The firmware's valid
filter domain is finite, and float-to-int callers must stay within signed32.
"""
from resonant_dsp import Emitter


def unpack(e, bits, prefix):
    sign, exponent, mantissa = (e.var(prefix + suffix) for suffix in ('sign', 'exp', 'mant'))
    e.shift(sign, bits, 31, signed=False)
    e.shift(exponent, bits, 23, signed=False)
    e.bits(exponent, exponent, 255)
    e.bits(mantissa, bits, 0x7FFFFF)
    subnormal, done = e.label(), e.label()
    e.compare(exponent, 0, 'beq', subnormal)
    e.bits(mantissa, mantissa, 0x800000, 'or')
    e.emit('bra ' + done)
    e.mark(subnormal)
    e.assign(exponent, 1)
    e.mark(done)
    return sign, exponent, mantissa


def pack(e, dst, sign, exponent, mantissa):
    temp = e.var('fp_pack_temp')
    e.bits(dst, mantissa, 0x7FFFFF)
    e.left(temp, exponent, 23)
    e.bits(dst, dst, temp, 'or')
    e.left(temp, sign, 31)
    e.bits(dst, dst, temp, 'or')


def round_even(e, mantissa, remainder, half, *, sticky=None):
    increment, done = e.label(), e.label()
    odd = e.var('fp_round_odd')
    e.compare(remainder, half, 'bgt', increment, signed=False)
    e.compare(remainder, half, 'blt', done, signed=False)
    if sticky is not None:
        e.compare(sticky, 0, 'bne', increment)
    e.bits(odd, mantissa, 1)
    e.compare(odd, 0, 'beq', done)
    e.mark(increment)
    e.add(mantissa, mantissa, 1)
    e.mark(done)


def right_jam(e, dst, value, amount):
    """Logical 32-bit shift, OR discarded nonzero bits into result bit zero."""
    large, done, no_lost = e.label(), e.label(), e.label()
    mask, lost = e.var('fp_jam_mask'), e.var('fp_jam_lost')
    e.assign(dst, value)
    e.compare(amount, 0, 'beq', done)
    e.compare(amount, 32, 'bge', large)
    e.left(mask, 1, amount)
    e.sub(mask, mask, 1)
    e.bits(lost, value, mask)
    e.shift(dst, value, amount, signed=False)
    e.compare(lost, 0, 'beq', no_lost)
    e.bits(dst, dst, 1, 'or')
    e.mark(no_lost)
    e.emit('bra ' + done)
    e.mark(large)
    e.compare(value, 0, 'beq', done)
    e.assign(dst, 1)
    e.mark(done)


def finish_round(e, sign, exponent, mantissa):
    no_overflow, done = e.label(), e.label()
    e.compare(mantissa, 0x1000000, 'blt', no_overflow, signed=False)
    e.shift(mantissa, mantissa, 1, signed=False)
    e.add(exponent, exponent, 1)
    e.mark(no_overflow)
    e.compare(exponent, 0, 'bne', done)
    e.compare(mantissa, 0x800000, 'blt', done, signed=False)
    e.assign(exponent, 1)
    e.mark(done)
    pack(e, e.var('fp_bits_out'), sign, exponent, mantissa)
    e.emit('rts')


def int_to_float(e):
    e.lines.append('pk_acoustic_int_to_float:')
    inp, out = e.var('fp_int_in'), e.var('fp_bits_out')
    sign, mag, exp, mant, rem = (e.var('fi_' + name) for name in ('sign', 'mag', 'exp', 'mant', 'rem'))
    nonzero = e.label()
    e.compare(inp, 0, 'bne', nonzero)
    e.assign(out, 0)
    e.emit('rts')
    e.mark(nonzero)
    e.shift(sign, inp, 31, signed=False)
    e.abs(mag, inp)
    e.assign(exp, 158)
    # Five decisions locate the highest bit; no sample-dependent 31-step loop.
    # Every step preserves the exact integer before the final single rounding.
    for shift in (16, 8, 4, 2, 1):
        ready = e.label()
        e.compare(mag, 1 << (32 - shift), 'bge', ready, signed=False)
        e.left(mag, mag, shift)
        e.sub(exp, exp, shift)
        e.mark(ready)
    e.shift(mant, mag, 8, signed=False)
    e.bits(rem, mag, 255)
    round_even(e, mant, rem, 128)
    finish_round(e, sign, exp, mant)


def decay(e):
    e.lines.append('pk_acoustic_float_decay:')
    inp, out = e.var('fp_bits_in'), e.var('fp_bits_out')
    sign, exp, mant = unpack(e, inp, 'fd_')
    nonzero, normalized, loop = e.label(), e.label(), e.label()
    e.compare(mant, 0, 'bne', nonzero)
    e.assign(out, inp)  # includes negative zero
    e.emit('rts')
    e.mark(nonzero)
    e.mark(loop)
    e.compare(mant, 0x800000, 'bge', normalized, signed=False)
    e.left(mant, mant, 1)
    e.sub(exp, exp, 1)
    e.emit('move #>' + loop + ',r3', 'jmp (r3)')
    e.mark(normalized)
    # Exact integer significand product for constant bits $3f7ae148.
    lo, hi, shift, temp, mask, rem, half = (e.var('fd_' + name) for name in
        ('lo', 'hi', 'shift', 'temp', 'mask', 'rem', 'half'))
    e.limbs(mant, 'x:(r5+$0)', 'x:(r5+$1)')
    e.limbs(0xFAE148, 'x:(r5+$2)', 'x:(r5+$3)')
    e.emit('jsr pk_u32_mul_full')
    e.assign(lo, ('r5', 8, 32))
    e.assign(hi, ('r5', 0x10, 32))
    lower, shift_ready = e.label(), e.label()
    e.bits(temp, hi, 0x8000)
    e.compare(temp, 0, 'beq', lower)
    e.assign(shift, 24)
    e.emit('bra ' + shift_ready)
    e.mark(lower)
    e.assign(shift, 23)
    e.sub(exp, exp, 1)
    e.mark(shift_ready)
    normal = e.label()
    e.compare(exp, 0, 'bgt', normal)
    e.sub(temp, 1, exp)
    e.add(shift, shift, temp)
    e.assign(exp, 0)
    e.mark(normal)
    upper_half, rounding_done = e.label(), e.label()
    e.compare(shift, 32, 'bge', upper_half)
    e.shift(mant, lo, shift, signed=False)
    e.sub(temp, 32, shift)
    e.left(temp, hi, temp)
    e.bits(mant, mant, temp, 'or')
    e.left(mask, 1, shift)
    e.sub(mask, mask, 1)
    e.bits(rem, lo, mask)
    e.sub(temp, shift, 1)
    e.left(half, 1, temp)
    round_even(e, mant, rem, half)
    e.emit('bra ' + rounding_done)
    e.mark(upper_half)
    e.sub(shift, shift, 32)
    e.shift(mant, hi, shift, signed=False)
    upper_nonzero, upper_done = e.label(), e.label()
    e.compare(shift, 0, 'bne', upper_nonzero)
    round_even(e, mant, lo, 0x80000000)
    e.emit('bra ' + upper_done)
    e.mark(upper_nonzero)
    e.left(mask, 1, shift)
    e.sub(mask, mask, 1)
    e.bits(rem, hi, mask)
    e.sub(temp, shift, 1)
    e.left(half, 1, temp)
    round_even(e, mant, rem, half, sticky=lo)
    e.mark(upper_done)
    e.mark(rounding_done)
    finish_round(e, sign, exp, mant)


def add(e):
    e.lines.append('pk_acoustic_float_add:')
    sx, ex, mx = unpack(e, e.var('fp_add_a'), 'fa_x_')
    sy, ey, my = unpack(e, e.var('fp_add_b'), 'fa_y_')
    swap, ordered = e.label(), e.label()
    e.compare(ex, ey, 'blt', swap)
    e.compare(ex, ey, 'bgt', ordered)
    e.compare(mx, my, 'bge', ordered, signed=False)
    e.mark(swap)
    temp = e.var('fa_temp')
    for x, y in ((sx, sy), (ex, ey), (mx, my)):
        e.assign(temp, x)
        e.assign(x, y)
        e.assign(y, temp)
    e.mark(ordered)
    diff = e.var('fa_diff')
    e.sub(diff, ex, ey)
    e.left(mx, mx, 3)
    e.left(my, my, 3)
    right_jam(e, my, my, diff)
    subtract, added = e.label(), e.label()
    e.compare(sx, sy, 'bne', subtract)
    e.add(mx, mx, my)
    e.emit('bra ' + added)
    e.mark(subtract)
    e.sub(mx, mx, my)
    e.mark(added)
    nonzero = e.label()
    e.compare(mx, 0, 'bne', nonzero)
    positive_zero = e.label()
    e.compare(sx, sy, 'bne', positive_zero)
    e.left(e.var('fp_bits_out'), sx, 31)
    e.emit('rts')
    e.mark(positive_zero)
    e.assign(e.var('fp_bits_out'), 0)
    e.emit('rts')
    e.mark(nonzero)
    no_overflow = e.label()
    e.compare(mx, 1 << 27, 'blt', no_overflow, signed=False)
    right_jam(e, mx, mx, 1)
    e.add(ex, ex, 1)
    e.mark(no_overflow)
    loop, normalized = e.label(), e.label()
    e.mark(loop)
    e.compare(mx, 1 << 26, 'bge', normalized, signed=False)
    e.left(mx, mx, 1)
    e.sub(ex, ex, 1)
    e.emit('move #>' + loop + ',r3', 'jmp (r3)')
    e.mark(normalized)
    normal = e.label()
    e.compare(ex, 0, 'bgt', normal)
    e.sub(diff, 1, ex)
    right_jam(e, mx, mx, diff)
    e.assign(ex, 0)
    e.mark(normal)
    rem = e.var('fa_rem')
    e.bits(rem, mx, 7)
    e.shift(mx, mx, 3, signed=False)
    round_even(e, mx, rem, 4)
    finish_round(e, sx, ex, mx)


def float_to_int(e):
    e.lines.append('pk_acoustic_float_to_int:')
    out = e.var('fp_int_out')
    sign, exp, mant = unpack(e, e.var('fp_bits_in'), 'ft_')
    nonzero, left, scaled, positive = (e.label() for _ in range(4))
    e.compare(exp, 127, 'bge', nonzero)
    e.assign(out, 0)
    e.emit('rts')
    e.mark(nonzero)
    shift = e.var('ft_shift')
    e.compare(exp, 150, 'bge', left)
    e.sub(shift, 150, exp)
    e.shift(out, mant, shift, signed=False)
    e.emit('bra ' + scaled)
    e.mark(left)
    e.sub(shift, exp, 150)
    e.left(out, mant, shift)
    e.mark(scaled)
    e.compare(sign, 0, 'beq', positive)
    e.sub(out, 0, out)
    e.mark(positive)
    e.emit('rts')


def kernels(e):
    int_to_float(e)
    decay(e)
    add(e)
    float_to_int(e)
