#!/usr/bin/env python3
"""Generate the final freestanding ColdFire Perky Machines assembly units.

Readable C stays authoritative.  Each C translation unit is emitted separately
so the normal Octabam DRAM linker resolves cross-unit symbols.  Firmware assets
are not part of this generation; cf_assets.s receives them at build time through
remix.inc after SHA verification.
"""
from __future__ import annotations

import argparse
from pathlib import Path
import re
import subprocess

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]

FLAGS = [
    "-mcpu=54455",
    "-msoft-float",
    "-O3",
    "-finline-functions",
    "-finline-limit=3000",
    "-funroll-loops",
    "-ffreestanding",
    "-fno-builtin",
    "-fno-common",
    "-fno-jump-tables",
    # A real ColdFire raises an address error on an odd-address word/long
    # access, but GCC's store-merging pass fuses two adjacent byte stores
    # (e.g. active_algo/active_mode at an odd struct offset) into one move.w at
    # an odd address -- which faults on silicon and is invisible to the
    # emulator. tools/verify/verify_perky_cf_odd_access.py audits for it.
    "-fno-store-merging",
    "-fno-asynchronous-unwind-tables",
    "-fno-ident",
    "-fomit-frame-pointer",
    "-fno-zero-initialized-in-bss",
    "-Wall",
    "-Wextra",
    "-Werror",
]

SOURCES = (
    ("pkcontrol", "control_cf_final.c"),
    ("pkcore", "cf_perky4.c"),
    ("pkfold", "cf_fold.c"),
    ("pkkarplus", "cf_karplus.c"),
    ("pknoise", "cf_noise_tone.c"),
    ("pkresonant", "cf_resonant.c"),
    ("pknoisehat", "cf_noise_hat.c"),
    ("pksimpledrum", "cf_simple_drum.c"),
    ("pkcomplexdrum", "cf_complex_drum.c"),
    ("pkslap", "cf_slap.c"),
)

# With the production source deliberately written in native 32-bit arithmetic,
# none of these runtime helpers should appear.  A new helper means a source or
# compiler change silently introduced an unlinked runtime dependency.
FORBIDDEN = re.compile(
    r"\b(?:__muldi3|__[us]divdi3|__[us]moddi3|__[us]divsi3|__[us]modsi3|memset|memcpy|memmove)\b"
)


def gcc_version() -> str:
    r = subprocess.run(
        ["m68k-elf-gcc", "-dumpfullversion"], check=True,
        capture_output=True, text=True,
    )
    return r.stdout.strip()


def generate(out_dir: Path) -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    version = gcc_version()
    outputs: list[Path] = []
    for label, name in SOURCES:
        source = HERE / name
        output = out_dir / f"{label}.s"
        subprocess.run(
            ["m68k-elf-gcc", *FLAGS, "-I", str(HERE), "-S", str(source), "-o", str(output)],
            cwd=ROOT,
            check=True,
        )
        body = output.read_text()
        bad = sorted(set(FORBIDDEN.findall(body)))
        if bad:
            raise SystemExit(
                f"PERKY CF: {name} emitted forbidden runtime helper(s): {', '.join(bad)}"
            )
        output.write_text(
            f"| Generated by generate_cf_final.py with m68k-elf-gcc {version}; edit {name}.\n"
            + body
        )
        outputs.append(output)
    return outputs


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=ROOT / "out/perky/cf-final")
    args = ap.parse_args()
    outputs = generate(args.out)
    print("PERKY CF generated freestanding ColdFire units:")
    for output in outputs:
        print(" ", output)


if __name__ == "__main__":
    main()
