#!/usr/bin/env python3
"""Generate PERKY's freestanding ColdFire assembly.

Readable C is authoritative. This intentionally uses the same compiler flags
as the hardware-qualified Analog BD source-machine module.

The default CLI still writes/checks ``modules/perky/control.s``. Development
builders may instead call ``generate_text()`` or pass ``--out`` so generated
assembly can live under ``out/`` without mutating tracked source files.
"""
from __future__ import annotations

import argparse
import pathlib
import subprocess
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
FLAGS = [
    "-mcpu=5407",
    "-msoft-float",
    "-O2",
    "-ffreestanding",
    "-fno-builtin",
    "-fno-common",
    "-fno-jump-tables",
    "-fno-asynchronous-unwind-tables",
    "-fno-ident",
    "-fomit-frame-pointer",
    "-fno-zero-initialized-in-bss",
    "-Wall",
    "-Wextra",
    "-Werror",
]


def generate_text(source: pathlib.Path | None = None) -> str:
    """Compile authoritative control.c and return deterministic assembly text."""
    source = source or HERE / "control.c"
    with tempfile.TemporaryDirectory(prefix="perky-control.") as tmp:
        generated = pathlib.Path(tmp) / "control.s"
        subprocess.run(
            ["m68k-elf-gcc", *FLAGS, "-S", str(source), "-o", str(generated)],
            check=True,
        )
        return "| Generated by generate.py; edit control.c.\n" + generated.read_text()


def write(output: pathlib.Path, source: pathlib.Path | None = None) -> str:
    """Generate and write assembly to an arbitrary repository-local path."""
    body = generate_text(source)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(body)
    return body


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="require the selected output to match generated control.c")
    ap.add_argument("--out", type=pathlib.Path, default=HERE / "control.s",
                    help="assembly output path")
    args = ap.parse_args()

    body = generate_text()
    if args.check:
        if not args.out.exists() or args.out.read_text() != body:
            raise SystemExit(f"stale: {args.out}")
        print(f"PERKY generated ColdFire source matches {args.out}")
        return

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(body)
    print(f"generated {args.out}")


if __name__ == "__main__":
    main()
