#!/usr/bin/env python3
"""Generate PERKY's freestanding ColdFire assembly.

Readable C is authoritative.  This intentionally uses the same compiler flags
as the hardware-qualified Analog BD source-machine module so generated output
can be checked into the tree and verified with ``--check``.
"""
from __future__ import annotations

import pathlib
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
FLAGS = [
    "-mcpu=5407",
    "-msoft-float",
    "-O2",
    "-ffreestanding",
    "-fno-builtin",
    "-fno-common",
    "-fno-jump-tables",
    "-fno-asynchronous-unwind-tables",
    "-fno-ident",
    "-fomit-frame-pointer",
    "-fno-zero-initialized-in-bss",
    "-Wall",
    "-Wextra",
    "-Werror",
]


def main() -> None:
    check = "--check" in sys.argv
    source = HERE / "control.c"
    output = HERE / "control.s"

    with tempfile.TemporaryDirectory() as tmp:
        generated = pathlib.Path(tmp) / "control.s"
        subprocess.run(
            ["m68k-elf-gcc", *FLAGS, "-S", str(source), "-o", str(generated)],
            check=True,
        )
        body = "| Generated by generate.py; edit control.c.\n" + generated.read_text()

    if check:
        if not output.exists() or output.read_text() != body:
            raise SystemExit(f"stale: {output}")
        print("PERKY generated ColdFire source matches")
    else:
        output.write_text(body)
        print(f"generated {output}")


if __name__ == "__main__":
    main()
