; Simple Drum's production PK/Y1 seam: prepared bytes, sample-offset retrigger.
pks_simple_entry:
        jsr pk_multi_simple_init
        move #>$3900,r5
        move #>$ffffff,m0
        move #>$ffffff,m1
        move #>$ffffff,m2
        move #>$ffffff,m3
        move #>$ffffff,m4
        move #>$ffffff,m5
        move #>$ffffff,m6
        move #$0,r0
        move x:(r4+$8),a
        and #>$ff,a
        asl #$8,a,a
        move x:(r4+$9),b
        and #>$ff,b
        move b1,x0
        add x0,a
        move a1,x:(r6+$20)
        move x:(r4+$a),a
        and #>$ff,a
        asl #$8,a,a
        move x:(r4+$b),b
        and #>$ff,b
        move b1,x0
        add x0,a
        move a1,x:(r6+$14)
        move x:(r4+$c),a
        and #>$ff,a
        asl #$8,a,a
        move x:(r4+$d),b
        and #>$ff,b
        move b1,x0
        add x0,a
        move a1,x:(r6+$1f)
        move x:(r4+$e),a
        and #>$ff,a
        asl #$8,a,a
        move x:(r4+$f),b
        and #>$ff,b
        move b1,x0
        add x0,a
        move a1,x:(r6+$21)
        move x:(r4+$11),a
        and #>$1,a
        move a1,x:(r6+$e)
        move #>$0802,a
        move a1,x:(r6+$9)
        move x:(r4+$10),a
        and #>$ff,a
        tst a
        beq pksd_mode0
        cmp #>$1,a
        beq pksd_mode1
        move #>$28a0,a
        bra pksd_mode_ready
pksd_mode0:
        move #>$22a0,a
        bra pksd_mode_ready
pksd_mode1:
        move #>$26a0,a
pksd_mode_ready:
        move a1,x:(r6+$8)
        move #>$10,a
        move a1,x:>$38ec
        move x:(r4+$3),a
        and #>$ffff,a
        tst a
        beq pksd_event_ready
        move x:>$20c,a
        tst a
        blt pksd_event_ready
        cmp #>$10,a
        bge pksd_event_ready
        move a1,x:>$38ec
pksd_event_ready:
        jsr pk_simple_base
        move x:>$38ec,a
        cmp #>$10,a
        beq pksd_full
        tst a
        beq pksd_retrigger
        move a1,n7
        jsr pk_simple_voice
pksd_retrigger:
        ; Authentic trigger: restart both envelopes and hold=1; preserve phase.
        move #>$1,a
        move a1,x:(r6+$a)
        move a1,x:(r6+$11)
        move a1,x:(r6+$15)
        move a1,x:(r6+$1c)
        clr a
        move a1,x:(r6+$f)
        move a1,x:(r6+$10)
        move a1,x:(r6+$12)
        move a1,x:(r6+$1a)
        move a1,x:(r6+$1b)
        move a1,x:(r6+$1d)
        move #>$10,a
        move x:>$38ec,x0
        sub x0,a
        move a1,n7
        jsr pk_simple_voice
        bra pks_continue
pksd_full:
        move #>$10,n7
        jsr pk_simple_voice
        bra pks_continue
